name: Deploy

on: 
  push:
    branches: [main, alpha, beta]
  # This tool encourages you to run it on pull requests to test the deployment process.
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:    
      contents: write # required to create git tags and releases
      pull-requests: write # allow commenting on PRs
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    
    - name: Run decaf to perform deployment
      uses: ./
      env:
        # required to use 'gh' CLI in my step scripts. 
        GH_TOKEN: ${{ github.token }}
      with: 
        compile_binary: 'true'
        github_token: ${{ secrets.github_token }}
        get_latest_release_current_branch: decaf shebang https://github.com/levibostian/decaf-script-github-releases-release-branch.git/shebang.sh@put-root-dir-env-var-in-input get --release-branch latest
        get_next_release_version: decaf shebang https://github.com/levibostian/decaf-script-conventional-commits.git/shebang.sh@0.3.1
        deploy: |
          OUTPUT_FILE_NAME=dist/bin-x86_64-Linux DENO_TARGET=x86_64-unknown-linux-gnu deno task compile
          OUTPUT_FILE_NAME=dist/bin-aarch64-Linux DENO_TARGET=aarch64-unknown-linux-gnu deno task compile
          OUTPUT_FILE_NAME=dist/bin-x86_64-Darwin DENO_TARGET=x86_64-apple-darwin deno task compile
          OUTPUT_FILE_NAME=dist/bin-aarch64-Darwin DENO_TARGET=aarch64-apple-darwin deno task compile 
          decaf shebang https://github.com/levibostian/decaf-script-git.git/shebang.sh@put-root-dir-env-var-in-input merge-into-release-branch --release-branch latest
          echo "{{nextVersionName}}" > version.txt
          cat version.txt
          decaf shebang https://github.com/levibostian/decaf-script-git.git/shebang.sh@put-root-dir-env-var-in-input commit-and-push --add version.txt 
          decaf shebang https://github.com/levibostian/decaf-script-github-releases-release-branch.git/shebang.sh@put-root-dir-env-var-in-input set-github-release-assets dist/bin-x86_64-Linux#x86_64-unknown-linux-gnu dist/bin-aarch64-Linux#aarch64-unknown-linux-gnu dist/bin-x86_64-Darwin#x86_64-apple-darwin dist/bin-aarch64-Darwin#aarch64-apple-darwin
          decaf shebang https://github.com/levibostian/decaf-script-github-releases-release-branch.git/shebang.sh@put-root-dir-env-var-in-input set --release-branch latest
