on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set up Deno
      uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4

    - name: Run formatter and fail if not formatted
      run: |
        deno fmt --check || (echo "Code has not been formatted. May I suggest you install git hooks on your development machine?" && exit 1)

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set up Deno
      uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4

    - name: Run lint and fail if there are errors
      run: |
        deno lint || (echo "Lint errors found. Please fix the issues above." && exit 1)