on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set up Deno
      uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4

    - name: Install dependencies
      run: deno install

    - name: Run Deno tests
      run: deno task test

    - name: Upload test results
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: junit-results
        path: reports/junit.xml

    - name: Upload coverage for analysis
      uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2
      with:
        file: reports/coverage.lcov
      env:
        # try and speedup the action by homebrew not having to do more then it needs when installing the coveralls tool
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true

    - name: Annotate failed tests
      if: always() # Run with test/lint failures.
      uses: granodigital/report-annotate@2eb4825bda241ef9a378669f1e7a3615d0be4d5d # v3.4.0
      with:
        reports: |
          junit|reports/junit.xml

  test-install-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Run install script
      run: ./install

    - name: Verify binary was installed
      run: which decaf